caractere = input('Digite qualquer tipo de caracter: ')
print('O caractere digitado é {} '.format(type(caractere)))
print('É alfanumerico?', caractere.isalnum())
print('É alfabético?', caractere.isalpha())
#print('', caractere.isascii())
print('É um número decimal?', caractere.isdecimal())
print('É um Digito?', caractere.isdigit())
print('Está em minusculas?', caractere.islower())
#print(''caractere.isidentifier())
print('Está em maiúsculas', caractere.isupper())
print('É mostravel?', caractere.isprintable())
print('A primeira é maiuscula?', caractere.istitle())
print('Só tem espaços?', caractere.isspace())
print('É um número?', caractere.isnumeric())
